# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Ezapiya-IDE_in_python\LogoForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(459, 455)
        MainWindow.setStyleSheet("QLabel{\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton{\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 420, 349, 29))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.btncopy = QtWidgets.QPushButton(self.layoutWidget)
        self.btncopy.setObjectName("btncopy")
        self.horizontalLayout.addWidget(self.btncopy)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(380, 420, 71, 30))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 0, 421, 421))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("E:/eZapiya/logo/IDE_Logo.png"))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ezapiya IDE"))
        self.label.setText(_translate("MainWindow", "GCC Is Not Found in AppData Folder "))
        self.btncopy.setText(_translate("MainWindow", "Install"))
        self.pushButton.setText(_translate("MainWindow", "Close"))

